# Generated by Django 5.1.3 on 2024-11-28 14:18

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('creator', models.CharField(max_length=200)),
                ('players', models.CharField(choices=[('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], max_length=10)),
                ('game_time', models.CharField(choices=[('15-30', '15-30 minutes'), ('30-60', '30-60 minutes'), ('60+', '60+ minutes')], max_length=50)),
                ('game_image_main', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('game_image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('game_image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('game_image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('game_image_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('game_brief', models.TextField()),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_commenter', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to='ssg_games.game')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
